# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  ldflags: -s -w -X main.version={{.Env.VERSION }} -X main.commit={{.Commit}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.VERSION }}-SNAPSHOT-{{ .Commit }}"
dist: dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
