language: go

go:
  - "1.11.x"
  - "1.12.x"

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - go: "1.x"
      os: osx

before_install:
  - make deps

script:
  - make lint
  - make unit
