language: go

go:
  - "1.x"
  - "1.11.x"
  - "1.12.x"

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - go: "1.x"
      os: osx

before_install:
  - make deps

script:
  - make lint
  - make unit
