version: "{build}"

image: Visual Studio 2019

# Source Config

clone_folder: c:\gopath\src\github.com\elastic\go-licenser

# Build host

environment:
  CGO_ENABLED: 0
stack: go 1.17

# Build

install:
  - choco install bzr
  - set Path=C:\Users\appveyor\go\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env

before_build:
  - go install

build_script:
  - appveyor AddCompilationMessage "Starting Compilation"
  - go install github.com/elastic/go-licenser

test_script:
  - go-licenser -d -exclude golden
  - go test -timeout 10s -p 4 -cover ./...
