# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-licenser
  description: Go Licenser - Adds a license header to any Go source files

spec:
  type: library
  owner: group:ingest-fp
  system: platform-ingest
  lifecycle: production
