# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - group: ":linux: Test matrix group"
    steps:
      - label: ":linux: Test matrix. Go {{matrix.go_version}}"
        key: test-matrix
        matrix:
          setup:
            go_version:
              - "1.20"
              - "1.19"
        command:
          - ".buildkite/scripts/test-on-platform.sh"
        agents:
          image: golang:{{matrix.go_version}}
          cpu: "8"
          memory: "4G"
