name: macos

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Install dependencies
      run: |
        export GOBIN=$PWD/bin
        mkdir -p $GOBIN/bin
        ls -ltra $GOBIN/bin
        echo "$GOBIN/bin"
        make deps
        ls -ltra $GOBIN/bin
        echo "$GOBIN/bin"

    - name: Run build
      run: make build

    - name: Run lint
      run: make lint

    - name: Run test
      run: make unit
