name: macos

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Install dependencies
      run: GOBIN=$PWD/bin make deps

    - name: Run build
      run: |
        ls -ltra $PWD/bin
        ls -ltra $GOBIN
        make lint

    - name: Run lint
      run: make lint

    - name: Run test
      run: make unit
